spring:
  application:
    name: api

  # Default active profile for local development
  profiles:
    active: dev

  # Load environment-specific configuration
  config:
    import: "classpath:env-${spring.profiles.active}.yml"

  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

# Security configuration
security:
  jwt:
    secret: ${JWT_SECRET}