spring:
  application:
    name: api

  # Default active profile for local development
  profiles:
    active: dev

  # Load environment-specific configuration
  config:
    import: "classpath:env-${spring.profiles.active}.yml"

  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Security configuration
security:
  jwt:
    secret: ${JWT_SECRET}