package com.chatop.api.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Message entity representing a message sent by a user regarding a rental.
 * Each message is associated with a sender (User) and a rental (Rental).
 * The message content and the timestamp of when it was sent are also stored.
 */
@Entity
@Table(name = "messages")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Message {

    /**
     * Unique identifier for the message.
     * This is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User who sent the message. This field is required and cannot be null.
     * This is a many-to-one relationship since one user can send multiple messages,
     * but each message has only one sender.
     */
    @ManyToOne
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;

    /**
     * Rental that the message is about. This field is required and cannot be null.
     * This is a many-to-one relationship since one rental can have multiple messages,
     * but each message is about only one rental.
     */
    @ManyToOne
    @JoinColumn(name = "rental_id", nullable = false)
    private Rental rental;

    /**
     * Content of the message sent by the user. This field is required and cannot be null.
     */
    @Lob
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Timestamp of when the message was sent. This field is required and cannot be null.
     * The value is automatically set to the current date and time when the message is created.
     */
    @Column(name = "sent_at", nullable = false)
    @CreationTimestamp
    private LocalDateTime sentAt;
}
