package com.chatop.api.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Rental entity representing a rental property in the system. Each rental has a name, surface area, price per night,
 * picture URL, description, and an associated owner (User). The entity also tracks creation and update timestamps.
 */
@Entity
@Table(name = "rentals")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Rental {

    /**
     * Unique identifier for the rental property.
     * This is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the rental property. This field is required and cannot be null.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Surface area of the rental property in square meters. This field is required and cannot be null.
     * The value is stored as a BigDecimal to allow for precise representation of decimal values.
     */
    @Column(name = "surface_area", nullable = false, precision = 10, scale = 2)
    private BigDecimal surfaceArea;

    /**
     * Price per night for renting the property. This field is required and cannot be null.
     * The value is stored as a BigDecimal to allow for precise representation of decimal values.
     */
    @Column(name = "price_per_night", nullable = false, precision = 10, scale = 2)
    private BigDecimal pricePerNight;

    /**
     * URL of the picture representing the rental property. This field is required and cannot be null.
     */
    @Column(name = "picture_url", nullable = false)
    private String pictureUrl;

    /**
     * Description of the rental property. This field is required and cannot be null.
     */
    @Lob
    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    /**
     * User who owns the rental property. This field is required and cannot be null.
     * This is a many-to-one relationship since one user can own multiple rentals,
     * but each rental has only one owner.
     */
    @ManyToOne
    @JoinColumn(name = "owner_id", nullable = false)
    private User owner;

    /**
     * Timestamp of when the rental was created. This field is required and cannot be null.
     * The value is automatically set to the current date and time when the rental is created
     */
    @Column(name = "created_at", nullable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp of when the rental was last updated. This field is required and cannot be null.
     * The value is automatically updated to the current date and time whenever the rental is updated.
     */
    @Column(name = "updated_at", nullable = false)
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
