package com.chatop.api.model;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import org.apache.commons.lang3.builder.ToStringExclude;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

/**
 * User entity representing a user in the system.
 * Each user has a unique email, a name, a password, and timestamps for when the user was created and last updated.
 * The email field is enforced to be unique across all users to prevent duplicate accounts.
 * The createdAt and updatedAt fields are automatically managed to track the lifecycle of the user entity.
 */
@Entity
@Table(name = "users", uniqueConstraints = {
        @UniqueConstraint(name = "uk_users_email", columnNames = "email")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    /**
     * Unique identifier for the user.
     * This is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the user. This field is required and cannot be null.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Email of the user. This field is required, cannot be null, and must be unique across all users.
     */
    @Column(name = "email", nullable = false)
    private String email;

    /**
     * Password of the user. This field is required and cannot be null.
     */
    @Column(name = "password_hash", nullable = false)
    @ToStringExclude
    private String passwordHash;

    /**
     * Timestamp of when the user was created. This field is required and cannot be null.
     * The value is automatically set to the current date and time when the user is created.
     */
    @Column(name = "created_at", nullable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp of when the user was last updated. This field is required and cannot be null.
     * The value is automatically updated to the current date and time whenever the user entity is updated
     */
    @Column(name = "updated_at", nullable = false)
    @UpdateTimestamp
    private LocalDateTime updatedAt;


    // ---------------------------------------------------------------------------
    // UserDetails interface methods for Spring Security
    // ---------------------------------------------------------------------------

    /**
     * @return Collection of GrantedAuthority representing the authorities granted to the user.
     * In this implementation, it returns an empty list, indicating that the user has no specific authorities or roles assigned.
     * This can be modified to return actual authorities based on the application's requirements.
     */
    @Override
    public @NonNull Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of();
    }

    /**
     * @return String representing the user's password hash.
     * This method is used by Spring Security for authentication purposes.
     */
    @Override
    public @Nullable String getPassword() {
        return passwordHash;
    }

    /**
     * @return String representing the username, which in this case is the user's email address.
     * This method is used by Spring Security for authentication purposes.
     */
    @Override
    public @NonNull String getUsername() {
        return email;
    }

    /**
     * @return boolean indicating whether the user account is non-expired.
     * By default, this returns true, but it can be overridden to implement custom logic for account expiration based on specific conditions or business rules.
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * @return boolean indicating whether the user account is non-locked.
     * By default, this returns true, but it can be overridden to implement custom logic for account locking based on specific conditions.
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * @return boolean indicating whether the user's credentials (password) are non-expired.
     * By default, this returns true, but it can be overridden to implement custom logic for credential expiration.
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * @return boolean indicating whether the user account is enabled.
     * By default, this returns true, but it can be overridden to implement custom logic for enabling or disabling user accounts.
     */
    @Override
    public boolean isEnabled() {
        return true;
    }
}
