package com.chatop.api.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * User entity representing a user in the system.
 * Each user has a unique email, a name, a password, and timestamps for when the user was created and last updated.
 * The email field is enforced to be unique across all users to prevent duplicate accounts.
 * The createdAt and updatedAt fields are automatically managed to track the lifecycle of the user entity.
 */
@Entity
@Table(name = "users", uniqueConstraints = {
        @UniqueConstraint(name = "uk_users_email", columnNames = "email")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Unique identifier for the user.
     * This is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the user. This field is required and cannot be null.
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Email of the user. This field is required, cannot be null, and must be unique across all users.
     */
    @Column(name = "email", nullable = false, length = 255)
    private String email;

    /**
     * Password of the user. This field is required and cannot be null.
     */
    @Column(name = "password", nullable = false, length = 255)
    private String passwordHash;

    /**
     * Timestamp of when the user was created. This field is required and cannot be null.
     * The value is automatically set to the current date and time when the user is created.
     */
    @Column(name = "created_at", nullable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp of when the user was last updated. This field is required and cannot be null.
     * The value is automatically updated to the current date and time whenever the user entity is updated
     */
    @Column(name = "update_at", nullable = false)
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
